// Start by going to a web page first, like this:
I.goTo(DATA.createOfferUrl)
I.see("Offer Dashboard")
I.click("//div[span[contains(.,'Offer Rules')]]/preceding-sibling::button")
I.see("Manage Your Offer Rules")
I.click("//button[contains(.,'Inactive')]")
I.click("Create Offer")
I.see("Choose an offer rule")
I.click("Next")
I.see("Choose a merchant")
I.fill("//input","Swarovskiii")
I.see("Swarovskiii")
I.pressEnter()
I.click("Next")
I.see("Do you want to target specific channel")
I.click("Next")
I.see("Your offer's content")
I.fill("//div[contains(@class,'public-DraftEditorPlaceholder-root')]", "test comment 1")
I.click("Next")
I.see("Terms and Conditions")
I.fill("//div[contains(@data-aid,'toolbar')]/following-sibling::div","test comment 2")
I.click("Next")
I.see("Do you want to restrict how long this promotion is valid for?")
I.click("Next")
I.see("Will you limit how many shoppers can redeem this offer?")
I.click("Next")
I.see("Add photos to your offer")
I.click("Next")
I.see("Your offer is all set!")
I.click("No, Save Changes")