// Start by going to a web page first, like this:
I.goTo(DATA.createOfferUrl)
I.see("Offer Dashboard")
I.click(DATA.createOfferBtn)
I.see("Choose an offer rule")
I.click(DATA.createOfferRuleBtn)
I.see("How do you want to reward customers?")
I.click(DATA.dollarDiscountBtn)
I.click("Next")
I.see("Do you want to target specific segments for this reward?")
I.click("Next")
I.see("Do you want to reward customers on every transaction?")
I.click("Next")
I.see("Minimum purchase required to activate offer")
I.fill(DATA.inputDollar, "50")
I.click("Next")
I.see("Your offer rules are set")
I.click(DATA.finishLaterBtn)
I.see("Offer rule successfully saved")